language: java

jdk:
- oraclejdk8

after_success:
# - bash <(curl -s https://codecov.io/bash) -t e2b47562-00fa-42dc-bd34-fe2aa306e559
- ./gradlew jacocoTestReport coveralls

after_failure:
- ./gradlew clean check --debug
