language: java

jdk:
  - oraclejdk8

before_script:
  - chmod +x gradlew

script:
  - ./gradlew check
  - ./gradlew jacocoTestReport

# uploader command executes and registers travis as builder
after_success:
  - bash <(curl -s https://codecov.io/bash) -t e2b47562-00fa-42dc-bd34-fe2aa306e559